"""Grade the live filtered-ANN run vs the exact oracle (Plan: VDBB filtered-search).

Parses the engine's #FILT transcript (ids + `Time:` lines per query/selectivity/run)
and the host-side oracle manifest, then reports recall@k and median latency per
filter SELECTIVITY — the curve that answers "does fused filter+vector hold recall
and stay fast as the predicate tightens?". Sibling of bench/live_report.py.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

_QSTART = re.compile(r"#FILT QSTART qid=(\d+) sel=(\d+) run=(\d+) tag=(\w+)")
_QEND = re.compile(r"#FILT QEND qid=(\d+) sel=(\d+) run=(\d+)")
_TIME = re.compile(r"Time:\s+([\d.]+)\s+ms")
_INT = re.compile(r"^\s*(\d+)\s*$")


def parse(raw: str) -> dict:
    """Return {(qid,sel): {"ids":[...first measured run...], "times":[measured ms]}}."""
    out: dict = defaultdict(lambda: {"ids": None, "times": []})
    cur = None
    cur_ids: list[int] = []
    for line in raw.splitlines():
        m = _QSTART.search(line)
        if m:
            qid, sel, run, tag = int(m[1]), int(m[2]), int(m[3]), m[4]
            cur = (qid, sel, run, tag)
            cur_ids = []
            continue
        if _QEND.search(line):
            cur = None
            continue
        if cur is None:
            continue
        qid, sel, run, tag = cur
        mt = _TIME.search(line)
        if mt:
            if tag == "RUN":
                out[(qid, sel)]["times"].append(float(mt[1]))
                # first measured run's ids are the answer set (deterministic across runs)
                if out[(qid, sel)]["ids"] is None:
                    out[(qid, sel)]["ids"] = list(cur_ids)
            continue
        mi = _INT.match(line)
        if mi:
            cur_ids.append(int(mi[1]))
    return out


def _median(xs: list[float]) -> float:
    if not xs:
        return 0.0
    s = sorted(xs)
    n = len(s)
    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2


def grade(parsed: dict, manifest: dict) -> dict:
    k = manifest["k"]
    oracle = manifest["oracle"]
    per_sel: dict = defaultdict(lambda: {"recall": [], "lat": []})
    for (qid, sel), rec in parsed.items():
        truth = oracle.get(f"{qid}:{sel}", [])
        got = rec["ids"] or []
        if truth:
            hit = len(set(got[:k]) & set(truth[:k]))
            per_sel[sel]["recall"].append(hit / min(k, len(truth)))
        if rec["times"]:
            per_sel[sel]["lat"].append(_median(rec["times"]))
    summary = {}
    for sel, d in sorted(per_sel.items()):
        rec = d["recall"]
        lat = d["lat"]
        summary[sel] = {
            "recall_at_k": sum(rec) / len(rec) if rec else 0.0,
            "median_latency_ms": _median(lat),
            "qps_per_conn": (1000.0 / _median(lat)) if lat and _median(lat) else 0.0,
            "n_queries": len(rec),
        }
    return summary


def render_md(summary: dict, manifest: dict) -> str:
    lines: list[str] = []
    w = lines.append
    w(
        "# TriDB Benchmark — Filtered Vector Search (VectorDBBench IntFilter methodology)"
    )
    w("")
    w(
        f"**Fused filter+vector with early termination on REAL SIFT-128.** Recall@{manifest['k']} "
        f"and latency vs filter SELECTIVITY (`WHERE label >= t ORDER BY emb <-> q LIMIT k`), "
        f"on {manifest['entities']} base vectors, {manifest['queries']} queries, "
        f"median of {manifest['runs']} warm runs."
    )
    w("")
    w("| selectivity (% pass) | recall@k | median latency (ms) | QPS / conn |")
    w("|---:|---:|---:|---:|")
    for sel in sorted(summary):
        s = summary[sel]
        w(
            f"| {sel}% | {s['recall_at_k']:.3f} | {s['median_latency_ms']:.3f} | "
            f"{s['qps_per_conn']:.0f} |"
        )
    w("")
    w("## Notes")
    w("")
    w(
        "- **Selectivity = % of rows the filter PASSES** (1% is the hard VDBB case: the "
        "predicate excludes 99% of the corpus). Recall is graded vs the EXACT filtered "
        "top-k numpy oracle on the same labels (deterministic from the seed)."
    )
    w(
        f"- **Dataset:** {manifest['source']}. Single warm connection; QPS/conn = "
        "1000/median-latency (concurrent QPS is the VDBB headline — run the recognized "
        "tool via bench/vdbb_tridb.py for the multi-client number)."
    )
    w(
        "- **Scale:** this is the bounded slice for the standin; the full SIFT-1M and the "
        "VDBB 768D1M1P/99P Cohere cases run on the GX10 (NEON HNSW)."
    )
    w("")
    w(
        "_Generated by `bench/filtered_report.py` (`make bench-filtered`). Numbers are observed._"
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Grade live filtered-ANN run.")
    ap.add_argument("--raw", type=Path, required=True)
    ap.add_argument("--manifest", type=Path, required=True)
    ap.add_argument(
        "--json-out", type=Path, default=Path("bench/results/filtered_metrics.json")
    )
    ap.add_argument(
        "--md-out", type=Path, default=Path("docs/benchmark_filtered_v0.1.0.md")
    )
    args = ap.parse_args(argv)

    manifest = json.loads(args.manifest.read_text())
    parsed = parse(args.raw.read_text())
    summary = grade(parsed, manifest)

    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(
        json.dumps(
            {
                "source": manifest["source"],
                "entities": manifest["entities"],
                "dim": manifest["dim"],
                "k": manifest["k"],
                "by_selectivity": summary,
            },
            indent=2,
        )
    )
    args.md_out.parent.mkdir(parents=True, exist_ok=True)
    args.md_out.write_text(render_md(summary, manifest))
    for sel in sorted(summary):
        s = summary[sel]
        print(
            f"[filtered] sel={sel}% recall@{manifest['k']}={s['recall_at_k']:.3f} "
            f"median={s['median_latency_ms']:.3f}ms"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
