"""Generate the LIVE-engine SM-2 timing SQL for the TriDB canonical query (DEV-1171).

Sibling of tools/bench_corpus.py. Where bench_corpus.py captures the TriDB side's
correctness + SM-3 (tjs_candidates_examined) + EXPLAIN-ANALYZE in-DB time, THIS
generator captures the like-for-like SM-2 number the head-to-head needs:

    END-TO-END CLIENT WALL-CLOCK per query over a WARM psql connection,
    the MEDIAN of >=N repeated runs of the SAME canonical tjs() query,
    with the one-time corpus load + HNSW index build EXCLUDED from timing.

This is the direct analog of how baseline/sm2.py times the multi-system baseline
(Python time.perf_counter() around each query over warm clients, median of N).
psql ``\\timing on`` reports the client-observed wall-clock of each statement
(round-trip: send + plan + execute + receive), which is exactly the client-side
end-to-end cost the baseline's perf_counter measures — so the two sides are
measured the same way.

It reuses tools/bench_corpus.py's deterministic corpus generation (same --seed
and params => the IDENTICAL entity ids, embeddings, edges, timestamps, and the
same per-query src/vector/window/k that the baseline loads). It writes the same
manifest.json so both sides are provably driven from one corpus.

FORK SAFETY (test/canonical_e2e_test.sql:130-139): each timed tjs() call is its
own top-level statement — never co-issued with a second scan of `entities` in one
plpgsql block. The repeated runs are independent top-level statements, which the
fork handles (the live bench already runs tjs() then EXPLAIN of the same call).

Output markers (machine-parseable, scraped by bench/sm2_compare.py):

    #SM2 QSTART qid=<q> src=<s> k=<k>
    Time: <ms> ms            <- one psql \\timing line per measured tjs() run
    #SM2 RESULT qid=<q> ids=<csv>
    #SM2 QEND qid=<q>
    #SM2 DONE
"""

from __future__ import annotations

import argparse
import json

from bench_corpus_shared import build_corpus, vec_literal


def build_sql(
    manifest: dict, runs: int, term_cond: int = 0, join_order: str = ""
) -> str:
    n = manifest["entities"]
    dim = manifest["dim"]
    k = manifest["k"]
    # DEV-1290: optionally emit the 8-arg tjs() form to pin the physical body ('vector_first'
    # or 'filter_first'); '' keeps the legacy 7-arg emission (engine-default vector-first).
    jo = f", '{join_order}'" if join_order else ""
    entities = manifest["_entities"]  # [(id, ts, embedding_list)]
    edges = manifest["_edges"]
    queries = manifest["queries"]

    lines: list[str] = []
    w = lines.append
    w(
        "-- AUTO-GENERATED by tools/bench_sm2_corpus.py — LIVE TriDB SM-2 timing (DEV-1171)."
    )
    w("-- Do not edit by hand; regenerate via scripts/bench_sm2.sh.")
    w(
        f"-- corpus={n} dim={dim} hubs={manifest['hubs']} fanout={manifest['fanout']} "
        f"queries={len(queries)} edges={len(edges)} k={k} runs={runs} term_cond={term_cond}"
    )
    w("\\set ON_ERROR_STOP on")

    # ----- one-time LOAD (UNTIMED): build corpus + native graph + HNSW index ---
    w("\\timing off")
    w("CREATE EXTENSION vectordb;")
    w(
        "CREATE EXTENSION graph_store_am;"
    )  # v1 native AM, v0-compat surface (ADR-0013 Stage B)
    w("CREATE TABLE entities (")
    w("    id        bigint PRIMARY KEY,")
    w("    chunk     text,")
    w("    ts        int,")
    w(f"    embedding float8[{dim}]")
    w(");")
    w("-- all rows BEFORE the index (HNSW fork limitation: no incremental insert).")
    batch = 500
    for i in range(0, n, batch):
        vals = []
        for eid, ts, emb in entities[i : i + batch]:
            vals.append(f"({eid},'chunk {eid}',{ts},'{vec_literal(emb)}'::float8[])")
        w(
            "INSERT INTO entities (id,chunk,ts,embedding) VALUES\n"
            + ",\n".join(vals)
            + ";"
        )
    w("CREATE INDEX entities_hnsw ON entities USING hnsw(embedding)")
    w(f"    WITH (dimension = {dim}, distmethod = l2_distance);")
    # ADR-0013 Stage B: vertex materialization pass — every edge endpoint's dense vid
    # is created up front through the ext-id map (gph_upsert_vertex) in FIRST-APPEARANCE
    # order, the exact vid assignment add_edge alone would produce, so entity ids, edges,
    # and manifests stay byte-identical to the v0-era corpus. add_edge (the v0-compat
    # shim hosted in graph_store_am) then routes each edge through the map:
    # gph_insert_edge(gph_upsert_vertex(s), gph_upsert_vertex(d)).
    _seen: set = set()
    _verts: list = []
    for s, d in edges:
        for v in (s, d):
            if v not in _seen:
                _seen.add(v)
                _verts.append(v)
    w("-- vertex materialization pass (ADR-0013 Stage B): ext ids -> dense vids")
    for i in range(0, len(_verts), 500):
        arr = ",".join(str(v) for v in _verts[i : i + 500])
        w(
            f"SELECT graph_store.gph_upsert_vertex(v) "
            f"FROM unnest(ARRAY[{arr}]::bigint[]) v;"
        )
    w(
        "-- native adjacency graph: hub -> dst (add_edge -> gph_insert_edge via the map)."
    )
    for s, d in edges:
        w(f"SELECT graph_store.add_edge({s}, {d});")
    w("SET enable_seqscan = off;   -- force the HNSW ANN scan for tjs's vector leg")

    # ----- WARM-UP: run each query once UNTIMED so caches/plan are primed -------
    w("-- warm-up (UNTIMED): prime every query once before the measured runs.")
    for q in queries:
        qid, src = q["qid"], q["src"]
        win = ",".join(str(t) for t in q["window"])
        qvec = vec_literal(q["embedding"])
        w(
            f"SELECT count(*) FROM tjs('entities', {k}, {term_cond}, {src}::bigint, 'id, chunk',"
            f"'ts IN ({win})', 'embedding <-> ''{qvec}'''{jo}) AS t(id bigint, chunk text);"
        )

    # ----- MEASURED: \\timing on, N repeated runs of the SAME tjs() per query ---
    w("\\timing on")
    for q in queries:
        qid, src = q["qid"], q["src"]
        win = ",".join(str(t) for t in q["window"])
        qvec = vec_literal(q["embedding"])
        w(f"\\echo #SM2 QSTART qid={qid} src={src} k={k}")
        for _ in range(runs):
            # each run: a single top-level tjs() statement (fork-safe). psql prints
            # a `Time: <ms> ms` line after each — the client-side wall-clock.
            w(
                f"SELECT t.id FROM tjs('entities', {k}, {term_cond}, {src}::bigint, 'id, chunk',"
                f"'ts IN ({win})', 'embedding <-> ''{qvec}'''{jo}) AS t(id bigint, chunk text);"
            )
        # capture the answer ids once (for SM-4 parity vs the baseline).
        w("\\timing off")
        w(
            f"SELECT '#SM2 RESULT qid={qid} ids=' || "
            "COALESCE(array_to_string(array_agg(id), ','), '') AS line FROM ("
        )
        w(
            f"  SELECT t.id FROM tjs('entities', {k}, {term_cond}, {src}::bigint, 'id, chunk',"
            f"'ts IN ({win})', 'embedding <-> ''{qvec}'''{jo}) AS t(id bigint, chunk text)"
        )
        w(") s;")
        w("\\timing on")
        w(f"\\echo #SM2 QEND qid={qid}")
    w("\\timing off")
    w("\\echo #SM2 DONE")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--entities", type=int, default=2000)
    p.add_argument("--dim", type=int, default=32)
    p.add_argument("--hubs", type=int, default=12)
    p.add_argument("--fanout", type=int, default=150)
    p.add_argument("--queries", type=int, default=12)
    p.add_argument("--k", type=int, default=5)
    p.add_argument("--window", type=int, default=600)
    p.add_argument("--time-min", type=int, default=19000)
    p.add_argument("--time-max", type=int, default=20000)
    p.add_argument("--query-jitter", type=float, default=0.35)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--runs", type=int, default=7, help="measured tjs() runs per query")
    p.add_argument(
        "--term-cond",
        type=int,
        default=0,
        help="tjs() early-termination depth (0 -> engine default 50). The recall/latency "
        "operating point; pin the SAME value for the SM-2 latency and recall claims.",
    )
    p.add_argument(
        "--join-order",
        choices=["", "vector_first", "filter_first"],
        default="",
        help="pin the tjs() physical body via the DEV-1290 8-arg form ('' = legacy 7-arg)",
    )
    p.add_argument("--sql-out", required=True)
    p.add_argument("--manifest-out", required=True)
    args = p.parse_args(argv)

    manifest = build_corpus(args)
    manifest["term_cond"] = (
        args.term_cond
    )  # recorded in the public manifest for sm2_compare
    manifest["join_order"] = args.join_order  # recorded for the report/provenance
    sql = build_sql(
        manifest, args.runs, term_cond=args.term_cond, join_order=args.join_order
    )

    # strip the bulky inline corpus arrays before writing the public manifest:
    # the baseline rebuilds them deterministically from the seed (same as the
    # TriDB live_report path), so the manifest only needs the metadata + queries.
    public = {k_: v for k_, v in manifest.items() if not k_.startswith("_")}

    with open(args.sql_out, "w") as f:
        f.write(sql)
    with open(args.manifest_out, "w") as f:
        json.dump(public, f)
    print(
        f"[bench_sm2_corpus] wrote {args.sql_out} + manifest {args.manifest_out} "
        f"(corpus={args.entities} dim={args.dim} queries={args.queries} k={args.k} "
        f"runs={args.runs} term_cond={args.term_cond} join_order={args.join_order or 'engine-default'})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
