"""Filtered vector-search corpus + exact oracle (VectorDBBench methodology).

Closes the on-thesis half of the VectorDBBench ask: FILTERED ANN — a relational
predicate combined with vector ordering, the case where TriDB's fused filter+vector
Index Scan with early termination (TR-1) should beat post-filtering. Mirrors VDBB's
IntFilter case (`WHERE int_field >= v ORDER BY emb <-> q LIMIT k`, selectivity set by
the threshold) on REAL SIFT-128 vectors (data/public/sift-128-euclidean.hdf5).

WHAT IS MEASURED vs GATED (same split as tools/real_corpus.py)
  host-side (no engine): the EXACT filtered top-k oracle per (query, selectivity),
    pure numpy — so recall is gradeable here.
  LIVE / GX10-gated: the engine's achieved recall + latency/QPS (scripts/bench_filtered.sh).
    The full VDBB 768D1M1P/99P case (Cohere 1M) runs via the bench/vdbb_tridb.py
    adapter on the GX10; this slice bounds the live run on the x86 standin.

Each base vector gets a uniform int label in [0,100); `WHERE label >= t` passes
~(100-t)% of rows, so t=99 -> ~1% selectivity (the hard VDBB filtered case), t=1 ->
~99%. Labels are deterministic from --seed so the oracle and the SQL agree.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

DEFAULT_SELECTIVITIES = [1, 10, 50, 99]  # percent of rows the filter PASSES


def _vec_literal(v) -> str:
    return "{" + ",".join(repr(float(x)) for x in v) + "}"


def load_sift(path: Path, *, limit: int, queries: int) -> tuple[np.ndarray, np.ndarray]:
    """Load (base[limit,d], query[queries,d]) from an ann-benchmarks hdf5."""
    import h5py

    with h5py.File(path, "r") as f:
        base = np.asarray(f["train"][:limit], dtype=np.float32)
        qry = np.asarray(f["test"][:queries], dtype=np.float32)
    return base, qry


def assign_labels(n: int, seed: int) -> np.ndarray:
    """Deterministic uniform int label in [0,100) per base vector."""
    return np.random.default_rng(seed).integers(0, 100, size=n, dtype=np.int64)


def _l2_sq(base: np.ndarray, q: np.ndarray) -> np.ndarray:
    diff = base - q
    return np.einsum("ij,ij->i", diff, diff)


def exact_filtered_topk(
    base: np.ndarray, labels: np.ndarray, q: np.ndarray, *, thresh: int, k: int
) -> list[int]:
    """Exact top-k ids among rows with label >= thresh, by true L2 (ties: id asc)."""
    mask = labels >= thresh
    ids = np.flatnonzero(mask)
    if ids.size == 0:
        return []
    d2 = _l2_sq(base[ids], q)
    order = np.lexsort((ids, d2))  # primary d2 asc, tie id asc
    return [int(ids[i]) for i in order[:k]]


def build(
    base: np.ndarray,
    query: np.ndarray,
    labels: np.ndarray,
    *,
    selectivities: list[int],
    k: int,
    runs: int,
) -> tuple[str, dict]:
    """Emit the #FILT live-engine SQL + a manifest carrying the exact oracle.

    selectivity p (% passing) -> threshold t = 100 - p, filter `WHERE label >= t`.
    """
    n, dim = base.shape
    thresholds = {p: max(0, 100 - p) for p in selectivities}

    lines: list[str] = []
    w = lines.append
    w(
        "-- AUTO-GENERATED by tools/filtered_corpus.py — LIVE filtered ANN (VDBB IntFilter)."
    )
    w("\\set ON_ERROR_STOP on")
    w("\\timing off")
    w("CREATE EXTENSION vectordb;")
    w(
        "CREATE TABLE vecs (id bigint PRIMARY KEY, label int, embedding float8[%d]);"
        % dim
    )
    batch = 500
    for i in range(0, n, batch):
        vals = ",".join(
            f"({j},{int(labels[j])},'{_vec_literal(base[j])}'::float8[])"
            for j in range(i, min(i + batch, n))
        )
        w(f"INSERT INTO vecs (id,label,embedding) VALUES {vals};")
    w("CREATE INDEX vecs_hnsw ON vecs USING hnsw(embedding)")
    w(f"    WITH (dimension = {dim}, distmethod = l2_distance);")

    # PHASE B — per query per selectivity, warm runs (median), printing ids + Time.
    oracle: dict = {}
    for qi in range(query.shape[0]):
        lit = _vec_literal(query[qi])
        for p in selectivities:
            t = thresholds[p]
            oracle[f"{qi}:{p}"] = exact_filtered_topk(
                base, labels, query[qi], thresh=t, k=k
            )
            for r in range(runs + 1):  # 1 warm-up + `runs` measured
                tag = "WARM" if r == 0 else "RUN"
                w(f"\\echo #FILT QSTART qid={qi} sel={p} run={r} tag={tag}")
                w("\\timing on")
                w(
                    f"SELECT id FROM vecs WHERE label >= {t} "
                    f"ORDER BY embedding <-> '{lit}' LIMIT {k};"
                )
                w("\\timing off")
                w(f"\\echo #FILT QEND qid={qi} sel={p} run={r}")
    w("\\echo #FILT DONE")

    manifest = {
        "source": "sift-128-euclidean (real)",
        "entities": n,
        "dim": dim,
        "queries": int(query.shape[0]),
        "k": k,
        "runs": runs,
        "selectivities": selectivities,
        "thresholds": thresholds,
        "oracle": oracle,
    }
    return "\n".join(lines) + "\n", manifest


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build filtered-ANN corpus + oracle.")
    ap.add_argument(
        "--hdf5", type=Path, default=Path("data/public/sift-128-euclidean.hdf5")
    )
    ap.add_argument("--limit", type=int, default=50000, help="base vectors (slice)")
    ap.add_argument("--queries", type=int, default=20)
    ap.add_argument("--k", type=int, default=10)
    ap.add_argument("--runs", type=int, default=5)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument(
        "--selectivities", type=int, nargs="+", default=DEFAULT_SELECTIVITIES
    )
    ap.add_argument("--sql-out", type=Path, required=True)
    ap.add_argument("--manifest-out", type=Path, required=True)
    args = ap.parse_args(argv)

    base, query = load_sift(args.hdf5, limit=args.limit, queries=args.queries)
    labels = assign_labels(base.shape[0], args.seed)
    sql, manifest = build(
        base,
        query,
        labels,
        selectivities=args.selectivities,
        k=args.k,
        runs=args.runs,
    )
    args.sql_out.write_text(sql)
    args.manifest_out.write_text(json.dumps(manifest))
    print(
        f"[filtered_corpus] {base.shape[0]} base, dim {base.shape[1]}, "
        f"{query.shape[0]} queries, k={args.k}, sel={args.selectivities} "
        f"-> {args.sql_out.name} + {args.manifest_out.name}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
