"""HNSW index-quality x term_cond recall/latency sweep (DEV-1286).

Emits ONE self-contained .sql that, run inside the NEON+reloptions tridb/msvbase
engine against a throwaway cluster, measures the recall/effort/latency curve the
DEV-1286 plan calls for:

  for each index config (m, ef_construction):       # build quality (reloptions, DEV-1286)
      CREATE INDEX ... WITH (m=.., ef_construction=..)   # NEON (DEV-1234) makes this affordable
      for each term_cond:                           # ANN search depth knob (DEV-1169)
          run the canonical tjs() query per query, print result ids, examined, EXPLAIN latency

The exact top-k ORACLE is computed HOST-SIDE in numpy (not in SQL), which (a) makes
recall@k gradeable without the engine and (b) sidesteps the fork's tjs()+second-scan
double-scan segfault (docs/fork_segfault_double_scan.md) — no in-session oracle scan runs.

Mirrors tools/bench_corpus.py for corpus/graph/query construction (kept self-contained
so the sweep can vary index reloptions and term_cond, which bench_corpus does not).
Deterministic via --seed. The live engine run is GX10/engine-gated; this module only
generates SQL + grades recall from a captured transcript.
"""

from __future__ import annotations

import argparse
import json
import re

import numpy as np


def _vec_literal(v) -> str:
    return "{" + ",".join(repr(float(x)) for x in v) + "}"


def _parse_pairs(spec: str) -> list[tuple[int, int]]:
    """'16:200,32:400' -> [(16,200),(32,400)]."""
    out = []
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        m, efc = part.split(":")
        out.append((int(m), int(efc)))
    return out


def build(args) -> tuple[str, dict]:
    rng = np.random.default_rng(args.seed)
    n, dim = args.entities, args.dim

    emb = rng.standard_normal((n, dim)).astype(np.float64)
    emb /= np.linalg.norm(emb, axis=1, keepdims=True)
    ts = rng.integers(args.time_min, args.time_max + 1, size=n)

    hubs = list(range(args.hubs))
    edges: list[tuple[int, int]] = []
    hub_dsts: dict[int, list[int]] = {}
    hub_centroids: dict[int, np.ndarray] = {}
    for h in hubs:
        centroid = rng.standard_normal(dim).astype(np.float64)
        centroid /= np.linalg.norm(centroid)
        hub_centroids[h] = centroid
        d2 = np.sum((emb - centroid) ** 2, axis=1)
        pool = np.argsort(d2)[: max(args.fanout * 3, args.fanout + 1)]
        dsts = rng.choice(pool, size=min(args.fanout, len(pool)), replace=False)
        dsts = [int(d) for d in dsts if int(d) != h]
        hub_dsts[h] = dsts
        edges.extend((h, d) for d in dsts)

    queries = []
    for qid in range(args.queries):
        h = hubs[qid % len(hubs)]
        qv = hub_centroids[h] + rng.standard_normal(dim) * args.query_jitter
        qv /= np.linalg.norm(qv)
        start = int(rng.integers(args.time_min, args.time_max - args.window + 2))
        window = list(range(start, start + args.window))
        # exact oracle (host-side): dst reachable from h, ts in window, nearest by true L2.
        win = set(window)
        cand = [d for d in hub_dsts[h] if int(ts[d]) in win]
        if cand:
            cd = np.array(cand)
            d2 = np.sum((emb[cd] - qv) ** 2, axis=1)
            order = cd[np.argsort(d2, kind="stable")]
            oracle = [int(x) for x in order[: args.k]]
        else:
            oracle = []
        queries.append(
            {
                "qid": qid,
                "src": h,
                "embedding": qv.tolist(),
                "window": window,
                "oracle": oracle,
            }
        )

    index_configs = _parse_pairs(args.index_configs)
    term_conds = [int(x) for x in args.term_conds.split(",") if x.strip()]

    manifest = {
        "entities": n,
        "dim": dim,
        "hubs": args.hubs,
        "fanout": args.fanout,
        "num_queries": len(queries),
        "k": args.k,
        "edges": len(edges),
        "seed": args.seed,
        "index_configs": index_configs,
        "term_conds": term_conds,
        "queries": queries,
    }

    # ---- SQL ----
    L: list[str] = []
    w = L.append
    w(
        "-- AUTO-GENERATED by tools/sweep_corpus.py — DEV-1286 index-quality x term_cond sweep."
    )
    w(
        f"-- corpus={n} dim={dim} hubs={args.hubs} fanout={args.fanout} queries={len(queries)} "
        f"k={args.k} configs={index_configs} term_conds={term_conds}"
    )
    w("\\set ON_ERROR_STOP on")
    w("\\timing off")
    w("CREATE EXTENSION vectordb;")
    w("CREATE EXTENSION graph_store;")
    w(
        "CREATE TABLE entities (id bigint PRIMARY KEY, chunk text, ts int, "
        f"embedding float8[{dim}]);"
    )
    batch = 500
    for i in range(0, n, batch):
        vals = ",".join(
            f"({j},'c{j}',{int(ts[j])},'{_vec_literal(emb[j])}'::float8[])"
            for j in range(i, min(i + batch, n))
        )
        w(f"INSERT INTO entities (id,chunk,ts,embedding) VALUES {vals};")
    for s, d in edges:
        w(f"SELECT graph_store.add_edge({s}, {d});")
    w("SET enable_seqscan = off;")

    for m, efc in index_configs:
        cfg = f"{m}_{efc}"
        w(f"\\echo #SWEEP BUILD_BEGIN cfg={cfg}")
        w("DROP INDEX IF EXISTS entities_hnsw;")
        w("\\timing on")
        w(
            f"CREATE INDEX entities_hnsw ON entities USING hnsw(embedding) "
            f"WITH (dimension={dim}, distmethod=l2_distance, m={m}, ef_construction={efc});"
        )
        w("\\timing off")
        w(f"\\echo #SWEEP BUILD_END cfg={cfg}")
        for tc in term_conds:
            for q in queries:
                qid, src = q["qid"], q["src"]
                qvec = _vec_literal(q["embedding"])
                win = ",".join(str(t) for t in q["window"])
                tag = f"cfg={cfg} tc={tc} qid={qid}"
                w(
                    f"SELECT '#SWEEP RESULT {tag} ids=' || "
                    "COALESCE(array_to_string(array_agg(id), ','), '') AS line FROM ("
                )
                w(
                    f"  SELECT t.id FROM tjs('entities', {args.k}, {tc}, {src}::bigint, "
                    f"'id, chunk', 'ts IN ({win})', 'embedding <-> ''{qvec}''') "
                    "AS t(id bigint, chunk text)) s;"
                )
                w(
                    f"SELECT '#SWEEP EXAMINED {tag} examined=' || tjs_candidates_examined() AS line;"
                )
                w(f"\\echo #SWEEP EXPLAIN_BEGIN {tag}")
                w(
                    f"EXPLAIN (ANALYZE, TIMING ON) SELECT t.id FROM tjs('entities', {args.k}, {tc}, "
                    f"{src}::bigint, 'id, chunk', 'ts IN ({win})', 'embedding <-> ''{qvec}''') "
                    "AS t(id bigint, chunk text);"
                )
                w(f"\\echo #SWEEP EXPLAIN_END {tag}")
    w("\\echo #SWEEP DONE")
    return "\n".join(L) + "\n", manifest


# --------------------------------------------------------------------------- #
# Parsing / grading a captured transcript.
# --------------------------------------------------------------------------- #
def _recall(returned: list[int], oracle: list[int]) -> float:
    if not oracle:
        return 1.0 if not returned else 0.0
    return len(set(returned) & set(oracle)) / len(oracle)


def report(manifest: dict, raw: str) -> dict:
    by_q = {q["qid"]: q for q in manifest["queries"]}
    k = manifest["k"]
    # cfg/tc -> {qid -> {ids, examined, ms}}
    rows: dict[tuple[str, int], dict[int, dict]] = {}
    build_ms: dict[str, float] = {}

    cur_cfg = None
    pend_explain = None  # (cfg, tc, qid)
    for line in raw.splitlines():
        s = line.strip()
        mb = re.search(r"#SWEEP BUILD_BEGIN cfg=(\S+)", s)
        if mb:
            cur_cfg = mb.group(1)
            continue
        # the CREATE INDEX timing prints "Time: NNNN.mmm ms" right after BUILD_BEGIN
        mt = re.match(r"Time:\s*([\d.]+)\s*ms", s)
        if mt and cur_cfg and cur_cfg not in build_ms:
            build_ms[cur_cfg] = float(mt.group(1))
            continue
        mr = re.search(r"#SWEEP RESULT cfg=(\S+) tc=(\d+) qid=(\d+) ids=(.*)$", s)
        if mr:
            cfg, tc, qid = mr.group(1), int(mr.group(2)), int(mr.group(3))
            ids = [int(x) for x in mr.group(4).split(",") if x.strip().isdigit()]
            rows.setdefault((cfg, tc), {}).setdefault(qid, {})["ids"] = ids
            continue
        me = re.search(
            r"#SWEEP EXAMINED cfg=(\S+) tc=(\d+) qid=(\d+) examined=(\d+)", s
        )
        if me:
            cfg, tc, qid = me.group(1), int(me.group(2)), int(me.group(3))
            rows.setdefault((cfg, tc), {}).setdefault(qid, {})["examined"] = int(
                me.group(4)
            )
            continue
        mx = re.search(r"#SWEEP EXPLAIN_BEGIN cfg=(\S+) tc=(\d+) qid=(\d+)", s)
        if mx:
            pend_explain = (mx.group(1), int(mx.group(2)), int(mx.group(3)))
            continue
        if pend_explain:
            mexec = re.search(r"Execution Time:\s*([\d.]+)\s*ms", s)
            if mexec:
                cfg, tc, qid = pend_explain
                rows.setdefault((cfg, tc), {}).setdefault(qid, {})["ms"] = float(
                    mexec.group(1)
                )
                pend_explain = None

    summary = []
    for (cfg, tc), qd in sorted(rows.items()):
        recalls, examined, lat = [], [], []
        for qid, obs in qd.items():
            if "ids" in obs:
                recalls.append(_recall(obs["ids"], by_q[qid]["oracle"]))
            if "examined" in obs:
                examined.append(obs["examined"])
            if "ms" in obs:
                lat.append(obs["ms"])
        summary.append(
            {
                "config": cfg,
                "term_cond": tc,
                "mean_recall@%d" % k: round(float(np.mean(recalls)), 4)
                if recalls
                else None,
                "mean_examined": round(float(np.mean(examined)), 1)
                if examined
                else None,
                "examined_pct": round(
                    100.0 * float(np.mean(examined)) / manifest["entities"], 3
                )
                if examined
                else None,
                "median_latency_ms": round(float(np.median(lat)), 3) if lat else None,
                "n": len(qd),
            }
        )
    return {
        "build_ms": build_ms,
        "sweep": summary,
        "corpus": manifest["entities"],
        "k": k,
    }


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--entities", type=int, default=30000)
    p.add_argument("--dim", type=int, default=256)
    p.add_argument("--hubs", type=int, default=16)
    p.add_argument("--fanout", type=int, default=200)
    p.add_argument("--queries", type=int, default=8)
    p.add_argument("--k", type=int, default=10)
    p.add_argument("--window", type=int, default=600)
    p.add_argument("--time-min", type=int, default=19000)
    p.add_argument("--time-max", type=int, default=20000)
    p.add_argument("--query-jitter", type=float, default=0.35)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--index-configs", default="16:200,32:400")
    p.add_argument("--term-conds", default="50,200,1000,5000")
    p.add_argument("--sql-out")
    p.add_argument("--manifest-out")
    p.add_argument("--report", help="grade a captured transcript against --manifest")
    p.add_argument("--manifest", help="manifest for --report mode")
    args = p.parse_args(argv)

    if args.report:
        with open(args.manifest) as f:
            manifest = json.load(f)
        with open(args.report) as f:
            raw = f.read()
        print(json.dumps(report(manifest, raw), indent=2))
        return 0

    sql, manifest = build(args)
    with open(args.sql_out, "w") as f:
        f.write(sql)
    with open(args.manifest_out, "w") as f:
        json.dump(manifest, f)
    print(
        f"[sweep_corpus] wrote {args.sql_out} (corpus={args.entities} dim={args.dim} "
        f"configs={manifest['index_configs']} term_conds={manifest['term_conds']}) "
        f"+ manifest {args.manifest_out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
