"""Fused (graph + vector) link prediction vs the cosine-only lower bound (DEV-1354).

This answers TriDB's core thesis in the cheapest possible way: given a bounded
candidate pool generated by embedding similarity, does GRAPH TOPOLOGY re-rank the
real hyperlinks higher than cosine alone? If yes, topology adds predictive signal
beyond the embedding; if fused == cosine, the thesis gets no support here.

DIRECT COMPARABILITY TO THE 0.110 LOWER BOUND
---------------------------------------------
tools/wiki_linkpredict.py measured a whole-corpus cosine-only overlap of 0.1101
(top-10 neighbour already an out-edge) over 5000 sampled sources (seed 42, pool =
k+buffer = 50) on the real 6,900,039-article / 224,475,283-edge enwiki artifact.
We reuse the SAME checkpoint, SAME seed/sample, SAME CAGRA candidate generation and
SAME overlap@10 protocol, so cosine-only here reproduces ~0.110 as a sanity check
and every other column is an apples-to-apples RE-RANK of the identical pool.

EARLY-TERMINATION RESPECT (TR-1)
--------------------------------
Candidate generation is bounded to each source's cosine top-`pool` neighbours (the
CAGRA kNN). Topology only RE-RANKS that pool — we never score all O(N^2) pairs, and
the topological adjacency we materialize is bounded to the source+candidate node set
(~3e5 nodes), not the full 6.9M. This mirrors the tjs_open bounded-pool design.

TOPOLOGICAL SCORERS (no training, computable from adjacency)
------------------------------------------------------------
For a source A and candidate B (predicting the directed link A->B):
  - Common Neighbours  CN(A,B) = |succ(A) ∩ succ(B)|
  - Adamic-Adar        AA(A,B) = Σ_{z ∈ succ(A)∩succ(B)} 1/log(indeg(z))
We use SUCCESSOR sets (out-neighbours) on both sides — i.e. the bibliographic-
coupling variant: "A and B point at many of the same pages." This is deliberately
bounded by out-degree (mean 31.5), so intersections stay cheap on 224M edges;
the undirected variant would pull in million-degree hub in-neighbourhoods and blow
the compute budget. The AA weight uses global IN-degree of the shared target z
(rarely-cited shared targets weigh more). Neither score reads the A->B bit, so there
is no label leakage into the topological features.
Note this is not label leakage but it IS a mild in-family signal: articles that link
to the same targets tend to link to each other — that is exactly the topological
prior we are testing.

FUSION
------
Reciprocal-rank fusion (RRF, parameter-light, scale-free) of the cosine rank and the
Adamic-Adar rank within the pool: score(B) = 1/(rrf_k + rank_cos) + 1/(rrf_k +
rank_aa). Top-10 by the fused score is then scored with the same overlap protocol.

NODE2VEC
--------
Skipped by design (reported as node2vec_included=false). Training node2vec on 6.9M
nodes / 224M edges means generating a multi-billion-token random-walk corpus and a
skip-gram training pass — a multi-hour-to-day job needing a training pipeline we do
not have here, and out of scope for the cheapest-test remit. CN/AA are training-free
and sufficient to answer the yes/no/marginal question.

HONEST BOUNDARIES (TriDB rules)
-------------------------------
- These embeddings are dim-384 float32 (bge-small), NOT the spec's dim-768 float8
  I/O-pressure basis — this is the compute-bound-ish regime, not the I/O regime.
- Counts are reconciled to the real corpus: 6,900,039 articles / 224,475,283 edges
  (the manifest bug lost shards 28/49/71; we trust the rebuilt shard files).
- This is a PREDICTIVE-SIGNAL test, not a speed claim. ADR-0017 says the I/O-bound
  regime is expected-fail; we make no latency claim here.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import pandas as pd

# Reuse the proven checkpoint loader + GPU CAGRA index path unchanged.
from wiki_linkpredict import build_cuvs_index, load_emb_checkpoint


# --------------------------------------------------------------------------- #
# Bounded adjacency: one streaming pass over the 224M-edge shards.
#   - global in-degree for every node (cheap bincount, used by Adamic-Adar)
#   - successor lists ONLY for the needed nodes (sources + candidates)
# Everything is in "pos space" = index into the sorted id array, so a node is a
# small int and set ops are numpy intersects on sorted arrays.
# --------------------------------------------------------------------------- #
def build_bounded_adjacency(
    corpus: Path,
    sorted_ids: np.ndarray,
    needed_pos: np.ndarray,
) -> tuple[np.ndarray, dict[int, np.ndarray], dict]:
    """Return (indeg[N], succ{pos->sorted-unique dst pos array}, stats).

    Single pass: indeg counts every valid edge's dst; succ keeps out-edges whose
    src is in `needed_pos` only. Edge endpoints not in the article set are dropped
    (matches the baseline's dst-in-`keep` filter)."""
    n = len(sorted_ids)
    needed_mask = np.zeros(n, dtype=bool)
    needed_mask[needed_pos] = True

    manifest = json.loads((corpus / "manifest.json").read_text())
    edge_files = [s["path"] for s in manifest["shards"]["edges"]["files"]]

    indeg = np.zeros(n, dtype=np.int64)
    src_chunks: list[np.ndarray] = []
    dst_chunks: list[np.ndarray] = []
    total_rows = 0
    valid_rows = 0
    t0 = time.time()
    for fi, name in enumerate(edge_files):
        df = pd.read_csv(
            corpus / name,
            sep="\t",
            header=None,
            names=["s", "d"],
            dtype=np.int64,
            engine="c",
        )
        s = df["s"].to_numpy()
        d = df["d"].to_numpy()
        total_rows += s.size
        # map ids -> pos via searchsorted; validate exact membership on both ends.
        sp = np.searchsorted(sorted_ids, s)
        dp = np.searchsorted(sorted_ids, d)
        np.clip(sp, 0, n - 1, out=sp)
        np.clip(dp, 0, n - 1, out=dp)
        valid = (sorted_ids[sp] == s) & (sorted_ids[dp] == d)
        sp = sp[valid]
        dp = dp[valid]
        valid_rows += sp.size
        # global in-degree over ALL valid edges (needed for Adamic-Adar weights)
        indeg += np.bincount(dp, minlength=n)
        # keep successors only for needed sources
        keep = needed_mask[sp]
        if keep.any():
            src_chunks.append(sp[keep].astype(np.int32))
            dst_chunks.append(dp[keep].astype(np.int32))
        if (fi + 1) % 12 == 0 or fi + 1 == len(edge_files):
            print(
                f"[fused] edge shard {fi + 1}/{len(edge_files)} "
                f"rows={total_rows:,} valid={valid_rows:,} "
                f"elapsed={time.time() - t0:.0f}s",
                flush=True,
            )

    all_src = np.concatenate(src_chunks) if src_chunks else np.empty(0, np.int32)
    all_dst = np.concatenate(dst_chunks) if dst_chunks else np.empty(0, np.int32)
    # group dst by src -> sorted unique successor array per needed source
    succ: dict[int, np.ndarray] = {}
    if all_src.size:
        order = np.argsort(all_src, kind="stable")
        s_sorted = all_src[order]
        d_sorted = all_dst[order]
        uniq, starts = np.unique(s_sorted, return_index=True)
        starts = np.append(starts, s_sorted.size)
        for i in range(uniq.size):
            a, b = starts[i], starts[i + 1]
            succ[int(uniq[i])] = np.unique(d_sorted[a:b])
    stats = {
        "edge_rows_read": int(total_rows),
        "edge_rows_valid": int(valid_rows),
        "needed_sources": int(needed_pos.size),
        "succ_nodes_materialized": len(succ),
        "adjacency_seconds": round(time.time() - t0, 1),
    }
    print(f"[fused] adjacency built: {stats}", flush=True)
    return indeg, succ, stats


def _overlap_at_k(order: np.ndarray, linked: np.ndarray, k: int) -> float:
    """Fraction of the top-k reranked candidates that are already out-edges."""
    top = order[:k]
    return float(linked[top].mean()) if top.size else 0.0


def run(corpus: Path, args: argparse.Namespace) -> dict:
    vecs, ids, model_name = load_emb_checkpoint(args.emb_in)
    ids_arr = np.asarray(ids, dtype=np.int64)
    n = ids_arr.size
    # pos space = index into sorted ids (so a node is a small sorted-array-friendly int)
    order = np.argsort(ids_arr)
    sorted_ids = ids_arr[order]
    print(
        f"[fused] loaded {n:,} embeddings from {args.emb_in} (model={model_name})",
        flush=True,
    )

    # SAME sampling as the baseline: seed 42, choice over rows of the checkpoint.
    rng = np.random.default_rng(args.seed)
    sample_n = min(args.sample, n)
    sample_rows = rng.choice(n, size=sample_n, replace=False)

    # ---- candidate generation: cosine kNN via the same CAGRA path -----------
    idx = build_cuvs_index(vecs, ids_arr, graph_degree=args.graph_degree)
    fetch = args.pool + 1  # +1 absorbs the self-hit
    q = np.ascontiguousarray(vecs[sample_rows])
    print(f"[fused] CAGRA kNN: {sample_n} sources x fetch={fetch}", flush=True)
    labels, dists = idx.knn_query(q, k=fetch)

    # per-source candidate id lists (self dropped, capped at pool) + cosine scores
    cand_ids: list[np.ndarray] = []
    cand_cos: list[np.ndarray] = []
    for row_i, r in enumerate(sample_rows):
        self_id = int(ids_arr[r])
        cids: list[int] = []
        ccos: list[float] = []
        for lab, d in zip(labels[row_i], dists[row_i]):
            lab = int(lab)
            if lab == self_id:
                continue
            cids.append(lab)
            ccos.append(1.0 - float(d))  # cuVS shim returns (1-cos); undo -> cosine
            if len(cids) >= args.pool:
                break
        cand_ids.append(np.asarray(cids, dtype=np.int64))
        cand_cos.append(np.asarray(ccos, dtype=np.float32))

    # ---- bounded adjacency over the real 224M-edge graph --------------------
    src_pos = np.searchsorted(sorted_ids, ids_arr[sample_rows])
    all_cand = np.concatenate(cand_ids) if cand_ids else np.empty(0, np.int64)
    cand_pos_all = np.searchsorted(sorted_ids, all_cand)
    needed_pos = np.unique(np.concatenate([src_pos, cand_pos_all]))
    indeg, succ, adj_stats = build_bounded_adjacency(corpus, sorted_ids, needed_pos)

    empty = np.empty(0, dtype=np.int32)
    aa_weight = 1.0 / np.log(np.maximum(indeg, 2).astype(np.float64))

    # ---- score + rerank each pool -------------------------------------------
    ov_cos: list[float] = []
    ov_cn: list[float] = []
    ov_aa: list[float] = []
    ov_fused: list[float] = []
    pool_base: list[float] = []
    out_deg: list[int] = []

    for row_i, r in enumerate(sample_rows):
        cids = cand_ids[row_i]
        cos = cand_cos[row_i]
        p = cids.size
        if p == 0:
            continue
        a_pos = int(np.searchsorted(sorted_ids, int(ids_arr[r])))
        sA = succ.get(a_pos, empty)  # A's out-edges (sorted, unique) == the labels
        out_deg.append(int(sA.size))

        cpos = np.searchsorted(sorted_ids, cids)
        # already-linked flag: candidate pos present in A's successor set
        if sA.size:
            hit = np.searchsorted(sA, cpos)
            np.clip(hit, 0, sA.size - 1, out=hit)
            linked = sA[hit] == cpos
        else:
            linked = np.zeros(p, dtype=bool)

        cn = np.zeros(p, dtype=np.float64)
        aa = np.zeros(p, dtype=np.float64)
        if sA.size:
            for j in range(p):
                sB = succ.get(int(cpos[j]), empty)
                if sB.size == 0:
                    continue
                common = np.intersect1d(sA, sB, assume_unique=True)
                if common.size:
                    cn[j] = common.size
                    aa[j] = float(aa_weight[common].sum())

        # rankings within the pool (stable => cosine order is the tie-break)
        cos_order = np.argsort(-cos, kind="stable")
        cn_order = np.argsort(-cn, kind="stable")
        aa_order = np.argsort(-aa, kind="stable")
        # RRF fuse cosine + Adamic-Adar
        rank_cos = np.empty(p, dtype=np.int64)
        rank_cos[cos_order] = np.arange(p)
        rank_aa = np.empty(p, dtype=np.int64)
        rank_aa[aa_order] = np.arange(p)
        rrf = 1.0 / (args.rrf_k + rank_cos) + 1.0 / (args.rrf_k + rank_aa)
        fused_order = np.argsort(-rrf, kind="stable")

        ov_cos.append(_overlap_at_k(cos_order, linked, args.k))
        ov_cn.append(_overlap_at_k(cn_order, linked, args.k))
        ov_aa.append(_overlap_at_k(aa_order, linked, args.k))
        ov_fused.append(_overlap_at_k(fused_order, linked, args.k))
        pool_base.append(float(linked.mean()))

    def m(x: list[float]) -> float:
        return round(float(np.mean(x)), 4) if x else 0.0

    cos_o, cn_o, aa_o, fused_o = m(ov_cos), m(ov_cn), m(ov_aa), m(ov_fused)
    best_topo = max(cn_o, aa_o)
    lift = round(fused_o - cos_o, 4)
    if fused_o <= cos_o + 0.002 and best_topo <= cos_o + 0.002:
        verdict = (
            "NO SUPPORT: topology does not re-rank the real hyperlinks above cosine. "
            f"Fused {fused_o} vs cosine {cos_o} (Δ{lift:+}). Within a semantically "
            "close pool the graph adds no separating signal here."
        )
    elif fused_o >= cos_o + 0.01:
        verdict = (
            f"TOPOLOGY ADDS SIGNAL: fused {fused_o} beats cosine {cos_o} "
            f"(Δ{lift:+}, {round(100 * lift / cos_o, 1)}% relative). Graph structure "
            "concentrates the true links higher than embedding proximity alone."
        )
    else:
        verdict = (
            f"MARGINAL: fused {fused_o} vs cosine {cos_o} (Δ{lift:+}); "
            f"best topo-only {best_topo}. A real but small lift — topology nudges the "
            "ranking but is not a decisive predictor on this pool."
        )

    return {
        "source": f"{corpus.name} (real, offline-wiki extraction)",
        "corpus": str(corpus),
        "articles_embedded": n,
        "corpus_truth": {"articles": 6900039, "edges": 224475283},
        "embed_model": model_name,
        "embed_dim": int(vecs.shape[1]),
        "embed_dtype": "float32 (bge-small; NOT the spec dim-768 float8 I/O basis)",
        "k": args.k,
        "pool": args.pool,
        "sampled": sample_n,
        "seed": args.seed,
        "candidate_generation": "cosine kNN via cuVS CAGRA (bounded pool, TR-1 respected)",
        "topological_scorers": {
            "common_neighbors": "|succ(A) ∩ succ(B)| (bibliographic coupling)",
            "adamic_adar": "Σ_{z∈succ(A)∩succ(B)} 1/log(indeg z)",
            "node2vec_included": False,
            "node2vec_skip_reason": (
                "training node2vec on 6.9M nodes / 224M edges = multi-billion-token "
                "walk corpus + skip-gram training, multi-hour job, out of scope for "
                "the cheapest-test remit; CN/AA are training-free"
            ),
        },
        "fusion": f"reciprocal-rank fusion(cosine, adamic_adar), rrf_k={args.rrf_k}",
        "overlap_at_k": {
            "cosine_only": cos_o,
            "common_neighbor_only": cn_o,
            "adamic_adar_only": aa_o,
            "fused": fused_o,
            "baseline_cosine_lower_bound": 0.1101,
            "pool_base_rate": m(pool_base),
            "mean_out_degree": round(float(np.mean(out_deg)), 4) if out_deg else 0.0,
            "note": (
                "fraction of each source's top-k reranked candidates that are already "
                "out-edges; candidate pool is the cosine top-`pool` for ALL columns, "
                "so cosine_only reproduces the 0.110 lower bound and the rest are pure "
                "reranks of the identical pool. pool_base_rate is the linked fraction "
                "over the whole pool (the reranking ceiling is set by how many true "
                "out-edges land in the cosine pool)."
            ),
        },
        "fused_vs_cosine_delta": lift,
        "verdict": verdict,
        "index": {
            "backend": "cuvs_cagra",
            "metric": "sqeuclidean (== cosine on unit vectors)",
            "graph_degree": args.graph_degree,
            "build_seconds": round(idx.build_s, 2),
        },
        "adjacency": adj_stats,
        "gating": (
            "compute-bound-ish (dim-384 f32) predictive-signal test, NOT a latency "
            "claim (ADR-0017: I/O regime is expected-fail). Real 224M-edge graph, "
            "bounded reranking pool."
        ),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--corpus", type=Path, default=Path("data/wiki/enwiki"))
    ap.add_argument(
        "--emb-in",
        type=Path,
        default=Path("data/wiki/enwiki/emb"),
        help="wiki_embed_hybrid checkpoint dir (vectors.f32 + ids.i64.npy + meta.json)",
    )
    ap.add_argument("--sample", type=int, default=5000, help="sources to score")
    ap.add_argument("--seed", type=int, default=42, help="MUST match the baseline (42)")
    ap.add_argument("--pool", type=int, default=50, help="cosine candidate pool size")
    ap.add_argument("--k", type=int, default=10, help="overlap@k")
    ap.add_argument("--graph-degree", type=int, default=32)
    ap.add_argument(
        "--rrf-k", type=int, default=60, help="reciprocal-rank fusion const"
    )
    ap.add_argument(
        "--json-out", type=Path, default=Path("bench/out/wiki_linkpred_fused.json")
    )
    args = ap.parse_args(argv)

    if not (args.corpus / "manifest.json").exists():
        ap.error(f"no manifest.json under {args.corpus}")
    if not (args.emb_in / "meta.json").exists():
        ap.error(f"no embedding checkpoint under {args.emb_in}")

    res = run(args.corpus, args)
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(res, ensure_ascii=False, indent=2))
    print(
        "\n=== FUSED LINK-PREDICTION (overlap@%d, %d sources) ==="
        % (args.k, res["sampled"])
    )
    o = res["overlap_at_k"]
    print(
        f"  cosine-only        : {o['cosine_only']}  (baseline {o['baseline_cosine_lower_bound']})"
    )
    print(f"  common-neighbor    : {o['common_neighbor_only']}")
    print(f"  adamic-adar        : {o['adamic_adar_only']}")
    print(f"  fused (RRF cos+AA) : {o['fused']}   Δ{res['fused_vs_cosine_delta']:+}")
    print(
        f"  pool base rate     : {o['pool_base_rate']}   mean out-deg {o['mean_out_degree']}"
    )
    print(f"\n  VERDICT: {res['verdict']}")
    print(f"\n[fused] wrote {args.json_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
